AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
    Description: ProjectName

  CodebaseVersion:
    Type: String
    Description: CodebaseVersion

  CodebaseBucketRegion:
    Type: String
    Description: CodebaseBucketRegion

  BackendEnv:
    Type: String
    Description: BackendEnv

Outputs:
  CodebaseBucketUrl:
    Fn::Join:
      - ""
      - - https://
        - !Ref ProjectName
        - -cfn.s3-
        - !Ref CodebaseBucketRegion
        - .amazonaws.com/
        - !Ref CodebaseVersion

#     SimRetrievalLambdaZipFile: lambda/sim-retrieval.zip
  SimRetrievalLambdaZipPath:
    Fn::Join:
      - !Ref CodebaseVersion
      - /lambda/sim-retrieval-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv
      - .zip

#     CreateSimLambdaZipFile: lambda/create-sim.zip
  CreateSimLambdaZipPath:
    Fn::Join:
      - !Ref CodebaseVersion
      - /lambda/create-sim-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv
      - .zip

#     DisableSimLambdaZipFile: lambda/disable-sim.zip
  DisableSimLambdaZipPath:
    Fn::Join:
      - !Ref CodebaseVersion
      - /lambda/disable-sim-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv
      - .zip

#     DeviceOnboardingLambdaZipFile: lambda/device-onboarding.zip
  DeviceOnboardingLambdaZipPath:
    Fn::Join:
      - !Ref CodebaseVersion
      - /lambda/device-onboarding-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv
      - .zip

#      OnboardingApiKeyName: device-onboarding-key
  OnboardingApiKeyName:
    Fn::Join:
      - device-onboarding-key-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

#      ApiGatewayUrlSSMParamName: openvpn-onboarding-api-gateway-url
  ApiGatewayUrlSSMParamName:
    Fn::Join:
      - device-onboarding-api-gateway-url-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

#      OnboardingPathSSMParamName: openvpn-onboarding-path
  OnboardingPathSSMParamName:
    Fn::Join:
      - device-onboarding-path-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

#      ProxyServerSSMParamName: openvpn-onboarding-proxy-server
#      BreakoutRegionSSMParamName: breakout-region

  SnsSuccessTopicName:
    Fn::Join:
      - success-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

  SnsFailureTopicName:
    Fn::Join:
      - failure-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

  SqsSimCreateQueueName:
    Fn::Join:
      - sims-create-fifo-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

  SqsSimDisableQueueName:
    Fn::Join:
      - sims-disable-fifo-
      - !Ref ProjectName
      - '-'
      - !Ref BackendEnv

  S3CodeOriginBucket:
    Fn::Join:
      - !Ref ProjectName
      - -cfn


#  ApiGatewayUrl:
#    Description: URL for API Gateway
#    Value:
#      Fn::Sub: https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com

#  CombinedParams:
#    Description: "Combined parameters"
#    Value:
#      Fn::Join:
#        - ":"
#        - [ !Ref Param1, !Ref Param2 ]

