AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
    Description: Project Name

  CodebaseVersion:
    Type: String
    Description: Codebase Version

  CodebaseBucketRegion:
    Type: String
    Description: Codebase Bucket Region

  BackendEnv:
    Type: String
    Description: Backend Env

  SimRetrievalLambdaNameBase:
    Type: String
    Default: sim-retrieval
    Description: Lambda name for sim-retrieval

  CreateSimLambdaNameBase:
    Type: String
    Default: create-sim
    Description: Lambda name for create-sim

  DisableSimLambdaNameBase:
    Type: String
    Default: disable-sim
    Description: Lambda name for disable-sim

  DeviceOnboardingLambdaNameBase:
    Type: String
    Default: device-onboarding
    Description: Lambda name for device-onboarding

Outputs:
  CodebaseBucketUrl:
    !Sub "https://${ProjectName}-cfn-templates-${BackendEnv}.s3-${CodebaseBucketRegion}.amazonaws.com/${CodebaseVersion}"

#  SimRetrievalLambdaName:
#    Fn::Join:
#      - ""
#      - 
#        - !Ref SimRetrievalLambdaNameBase
#        - "-"
#        - !Ref ProjectName
#        - "-"
#        - !Ref BackendEnv
  SimRetrievalLambdaName:
    !Sub "${SimRetrievalLambdaNameBase}-${ProjectName}-${BackendEnv}"

#  SimRetrievalLambdaZipPath:
#    Fn::Join:
#      - ""
#      -
#        - !Ref CodebaseVersion
#        - "/"
#        - !Ref SimRetrievalLambdaNameBase
#        - "-"
#        - !Ref ProjectName
#        - "-"
#        - !Ref BackendEnv
#        - .zip
  SimRetrievalLambdaZipPath:
    !Sub "${CodebaseVersion}/${SimRetrievalLambdaNameBase}-${ProjectName}-${BackendEnv}.zip"

  CreateSimLambdaName:
    !Sub "${CreateSimLambdaNameBase}-${ProjectName}-${BackendEnv}"

  CreateSimLambdaZipPath:
    !Sub "${CodebaseVersion}/${CreateSimLambdaNameBase}-${ProjectName}-${BackendEnv}.zip"

  DisableSimLambdaName:
    !Sub "${DisableSimLambdaNameBase}-${ProjectName}-${BackendEnv}"

  DisableSimLambdaZipPath:
    !Sub "${CodebaseVersion}/${DisableSimLambdaNameBase}-${ProjectName}-${BackendEnv}.zip"

  DeviceOnboardingLambdaName:
    !Sub "${DeviceOnboardingLambdaNameBase}-${ProjectName}-${BackendEnv}"

  DeviceOnboardingLambdaZipPath:
    !Sub "${CodebaseVersion}/${DeviceOnboardingLambdaNameBase}-${ProjectName}-${BackendEnv}.zip"

  OnboardingApiKeyName:
    !Sub "device-onboarding-key-${ProjectName}-${BackendEnv}"

#      ApiGatewayUrlSSMParamName: openvpn-onboarding-api-gateway-url
  ApiGatewayUrlSSMParamName:
    !Sub "device-onboarding-api-gateway-url-${ProjectName}-${BackendEnv}"

#      OnboardingPathSSMParamName: openvpn-onboarding-path
  OnboardingPathSSMParamName:
    !Sub "device-onboarding-path-${ProjectName}-${BackendEnv}"

#      ProxyServerSSMParamName: openvpn-onboarding-proxy-server
#      BreakoutRegionSSMParamName: breakout-region

  SnsSuccessTopicName:
    !Sub "success-${ProjectName}-${BackendEnv}"

  SnsFailureTopicName:
    !Sub "failure-${ProjectName}-${BackendEnv}"

  SqsSimCreateQueueName:
    !Sub "sims-create-fifo-${ProjectName}-${BackendEnv}"

  SqsSimDisableQueueName:
    !Sub "sims-disable-fifo-${ProjectName}-${BackendEnv}"

  S3CodeOriginBucket:
    !Sub "sims-disable-fifo-${ProjectName}-cfn-templates-${BackendEnv}"


#  ApiGatewayUrl:
#    Description: URL for API Gateway
#    Value:
#      Fn::Sub: https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com

#  CombinedParams:
#    Description: "Combined parameters"
#    Value:
#      Fn::Join:
#        - ":"
#        - [ !Ref Param1, !Ref Param2 ]

