AWSTemplateFormatVersion: "2010-09-09"
Description: Generates Secrets Manager entries
Parameters:
  #=======================================================
  #
  #                   CloudFormation Parameters
  #
  #=======================================================
  ManagementApiUsername:
    Type: String
    Description: Management API username
    MinLength: 1
  ManagementApiPassword:
    Type: String
    Description: Management API password
    MinLength: 1
    NoEcho: true
Resources:
  #=======================================================
  #
  #         Secrets manager parameters resources
  #
  #=======================================================
  ManagementApiCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: open-source-device-onboarding-management-api-credentials
      Description: Management API credentials
      SecretString:
        Fn::Sub: '{"username":"${ManagementApiUsername}", "password": "${ManagementApiPassword}"}'
Outputs:
  #=======================================================
  #
  #                 CloudFormation Outputs
  #
  #=======================================================
  ManagementApiCredentialsSecretARN:
    Description: Secret ARN of Management API credentials
    Value:
      Ref: ManagementApiCredentialsSecret

